package org.droidmate.exploration.modelFeatures.atua.inputRepo.textInput

import kotlin.random.Random

open class DataField (val name: String,
                 val resourceIdPatterns: ArrayList<String> = ArrayList(),
                 val textHintPatterns: ArrayList<String> = ArrayList(),
                 val informationType: InformationType) {
    init {
        if (!informationType.dataFields.contains(this))
        {
            informationType.dataFields.add(this)
        }
    }
}

open class AutoGeneratedDataField(name: String,
                                  resourceIdPatterns: ArrayList<String> = ArrayList(),
                                  textHintPatterns: ArrayList<String> = ArrayList(),
                                  informationType: InformationType): DataField(name, resourceIdPatterns, textHintPatterns, informationType){
    val posssibleValue = ArrayList<String>()
    val random = java.util.Random(Random.nextLong())
    fun getValue(): String{
        if (posssibleValue.isEmpty())
            return ""
        else
            return posssibleValue[random.nextInt(posssibleValue.size)]
    }
}

class DayDataField(informationType: InformationType): AutoGeneratedDataField(
        name = "Day", informationType = informationType){
    init {
        var i:Int = 1
        while (i<=31)
        {
            posssibleValue.add(i.toString())
            i++
        }
    }
}

class MonthDataField(informationType: InformationType): AutoGeneratedDataField(
        name="Month", informationType = informationType){
    init {
        var i:Int = 1
        while (i<=12)
        {
            posssibleValue.add(i.toString())
            i++
        }
    }
}

